### ISSUE TITLE
How to show number of  unread message ?

### ISSUE THREAD

**Issue by zgpnuaa** [narrowfail/django-channels-chat#10]
hi,
   This progect is great , thank you. 
Now i want to show number of  unread message in top right corner of name , how do i make it? Should i create new database table to mark read and unread ?

**Comment by narrowfail** [comment]
Hello, sorry for the late response. Right now the system does not know when a message has been read or not. You could add a database field, and then implement a mechanism in JS to change the messages statuses using the API.
