### ISSUE TITLE
Django channels not working on Https

### ISSUE THREAD

**Issue by SathishRavichandran** [narrowfail/django-channels-chat#12]
Not Found: /ws
[10/Dec/2019 10:04:44] "GET /ws?session_key=${sessionKey} HTTP/1.1" 404 23621

while running the setup with ssl server its not working. when i run in http its working

**Comment by narrowfail** [comment]
Did you follow the Django Channels deploy instructions?

https://channels.readthedocs.io/en/latest/deploying.html

Regards,
Guillermo

**Comment by SathishRavichandran** [comment]
No iam running on python manage.py run sslserver. It automatically takes to https..while using like this it's not working

**Comment by narrowfail** [comment]
That is not the way of running the project with SSL (using django-sslserver).  Please follow the instructions for doing the deploy.

**Comment by SathishRavichandran** [comment]
Hai.
Then we need to set up a proper web server like nginix in production?
then we need to rum daphine as background job like in supervisor .

**Comment by narrowfail** [comment]
Hello, yes you should follow the guide. The example with nginx looks good to me!
