### ISSUE TITLE
Can you put a requirements.txt file at the base directory of this repository?

### ISSUE THREAD

**Issue by sanjaypradeep** [narrowfail/django-channels-chat#18]
Reason for the need : any developers/learners who wanna fork/clone this repository would get better idea on what Django Packages we may need to build and test this.

Much appreciated.

**Comment by narrowfail** [comment]
Hello, 
we are using Pipenv instead of pip. You can get an idea of which packages are needed by taking a look at the following file:

https://github.com/narrowfail/django-channels-chat/blob/master/Pipfile

I think the setup instructions are pretty clear. What do you think?

Regards,
Guillermo
