### ISSUE TITLE
what is redis use for in this case?

### ISSUE THREAD

**Issue by aldwnesx** [narrowfail/django-channels-chat#19]
I am trying to understand how the code works.

When user A sends message to user B, it saves the message to database right away. Then notify user B of new incoming message via web socket.

Does thwe web socket retrieve from redis? or from rds? what is the use of redis?

can I set it that User B receives the message directly, or receive notification to check the database for newes dtaa?

**Comment by narrowfail** [comment]
Please take a look at the Django Channels Docummentation: https://channels.readthedocs.io/en/latest/topics/channel_layers.html?highlight=redis#channel-layers
