### ISSUE TITLE
Sending a message notification vs sending the message itself

### ISSUE THREAD

**Issue by realsuayip** [narrowfail/django-channels-chat#36]
Its indicated that:

> When the frontend receives a new message notification (with the message ID), 
> it performs a GET query to the API to download the received message.

Could you explain the reasoning behind this? Why not just send the message
itself via websocket? İ'm also considering using this design but İ can't find a reasoning
not to do the other way.

**Comment by narrowfail** [comment]
Hello @realsuayip! Sure, by using a rest API you have more features to control the traffic. Throttling is just one example: https://www.django-rest-framework.org/api-guide/throttling/.

**Comment by realsuayip** [comment]
So, as I understand, you want to make use of HTTP stuff while transferring data to client. But in the context of "transferring data" only, do you know if there are other implications? For example, which way is more likely to ensure consistent flow of data, e.g., order of messages.

And how about security & server load? I'm trying to figure out the best practice on this. Thanks!
