### ISSUE TITLE
django-channels > 2.x

### ISSUE THREAD

**Issue by sebastian-code** [narrowfail/django-channels-chat#4]
Hi. Great project, thanks for the hard work. Just one short question, do you have plans to upgrade the project to a more recent version of `django-channels`?

**Comment by narrowfail** [comment]
Hello, not right now, but you can do it if you want. Just open a pull request :smiley: !

**Comment by redliu312** [comment]
@narrowfail   I open a pull request to use channels 2.
#6

**Comment by narrowfail** [comment]
Awesome! Thansk for your work! @redliu312

**Comment by redliu312** [comment]
@narrowfail  forget to tell u , I learned a lot from ur architecture . thanks for your project
