### ISSUE TITLE
Can i connect this with sqlite3 db? for development purpose!   

### ISSUE THREAD

**Issue by soorajpazeekal** [narrowfail/django-channels-chat#5]
Can you share a tutorial or doc about how to sync this with on "sqlite" Database?

**Comment by narrowfail** [comment]
Just change the database conector and skip to the migrate parte.

`
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'mydatabase',
    }
}
`
