### ISSUE TITLE
Add requirements.txt file for project dependencies

### ISSUE THREAD

**Issue by WajahatKanju** [narrowfail/django-channels-chat#53]
While the absence of a requirements.txt file may not pose a significant challenge in simpler cases, it becomes increasingly crucial as the application scales. In larger projects, where multiple developers are involved, and the codebase evolves over time, having a centralized file like requirements.txt becomes indispensable.

As the project grows, managing dependencies without a clear specification can lead to version conflicts, making it difficult to maintain a consistent and stable development environment. The requirements.txt file serves as a snapshot of the dependencies at a specific point in time, ensuring that all contributors are on the same page and reducing the likelihood of compatibility issues as the codebase expands.

Therefore, even in the current simplicity of the project, proactively adding a requirements.txt file lays the groundwork for future scalability and fosters good development practices.

**Comment by narrowfail** [comment]
We are using Pipenv for dependency management. Please take a look at the readme and also take a look here: 

https://github.com/narrowfail/django-channels-chat/blob/master/Pipfile

Regards,
Guillermo
